import mongoose, { Schema, model } from "mongoose";

const institutionSchema = new Schema(
  {
    schoolName: {
      type: String,
      required: true,
    },
    schoolOwner: {
      type: String,
      // required: true,
      default: "",
    },
    schoolShortName: {
      type: String,
      required: true,
    },
    schoolType: {
      type: String,
      // required: true,
      default: "",
    },
    schoolMotto: {
      type: String,
      // required: true,
      default: "",
    },
    schoolAddress: {
      type: String,
      // required: true,
      default: "",
    },
    country: {
      type: String,
      required: true,
      enum: [
        "AFGHANISTAN",
        "ALBANIA",
        "ALGERIA",
        "ANDORRA",
        "ANGOLA",
        "ANTIGUA AND BARBUDA",
        "ARGENTINA",
        "ARMENIA",
        "AUSTRALIA",
        "AUSTRIA",
        "AZERBAIJAN",
        "THE BAHAMAS",
        "BAHRAIN",
        "BANGLADESH",
        "BARBADOS",
        "BELARUS",
        "BELGIUM",
        "BELIZE",
        "BENIN",
        "BHUTAN",
        "BOLIVIA",
        "BOSNIA AND HERZEGOVINA",
        "BOTSWANA",
        "BRAZIL",
        "BRUNEI",
        "BULGARIA",
        "BURKINA FASO",
        "BURUNDI",
        "CABO VERDE",
        "CAMBODIA",
        "CAMEROON",
        "CANADA",
        "CENTRAL AFRICAN REPUBLIC",
        "CHAD",
        "CHILE",
        "CHINA",
        "COLOMBIA",
        "COMOROS",
        "CONGO, DEMOCRATIC REPUBLIC OF THE",
        "CONGO, REPUBLIC OF THE",
        "COSTA RICA",
        "CÔTE D'IVOIRE",
        "CROATIA",
        "CUBA",
        "CYPRUS",
        "CZECH REPUBLIC",
        "DENMARK",
        "DJIBOUTI",
        "DOMINICA",
        "DOMINICAN REPUBLIC",
        "EAST TIMOR (TIMOR-LESTE)",
        "ECUADOR",
        "EGYPT",
        "EL SALVADOR",
        "EQUATORIAL GUINEA",
        "ERITREA",
        "ESTONIA",
        "ESWATINI",
        "ETHIOPIA",
        "FIJI",
        "FINLAND",
        "FRANCE",
        "GABON",
        "THE GAMBIA",
        "GEORGIA",
        "GERMANY",
        "GHANA",
        "GREECE",
        "GRENADA",
        "GUATEMALA",
        "GUINEA",
        "GUINEA-BISSAU",
        "GUYANA",
        "HAITI",
        "HONDURAS",
        "HUNGARY",
        "ICELAND",
        "INDIA",
        "INDONESIA",
        "IRAN",
        "IRAQ",
        "IRELAND",
        "ISRAEL",
        "ITALY",
        "JAMAICA",
        "JAPAN",
        "JORDAN",
        "KAZAKHSTAN",
        "KENYA",
        "KIRIBATI",
        "KOREA, NORTH",
        "KOREA, SOUTH",
        "KOSOVO",
        "KUWAIT",
        "KYRGYZSTAN",
        "LAOS",
        "LATVIA",
        "LEBANON",
        "LESOTHO",
        "LIBERIA",
        "LIBYA",
        "LIECHTENSTEIN",
        "LITHUANIA",
        "LUXEMBOURG",
        "MADAGASCAR",
        "MALAWI",
        "MALAYSIA",
        "MALDIVES",
        "MALI",
        "MALTA",
        "MARSHALL ISLANDS",
        "MAURITANIA",
        "MAURITIUS",
        "MEXICO",
        "MICRONESIA",
        "MOLDOVA",
        "MONACO",
        "MONGOLIA",
        "MONTENEGRO",
        "MOROCCO",
        "MOZAMBIQUE",
        "MYANMAR (BURMA)",
        "NAMIBIA",
        "NAURU",
        "NEPAL",
        "NETHERLANDS",
        "NEW ZEALAND",
        "NICARAGUA",
        "NIGER",
        "NIGERIA",
        "NORTH MACEDONIA (FORMERLY MACEDONIA)",
        "NORWAY",
        "OMAN",
        "PAKISTAN",
        "PALAU",
        "PANAMA",
        "PAPUA NEW GUINEA",
        "PARAGUAY",
        "PERU",
        "PHILIPPINES",
        "POLAND",
        "PORTUGAL",
        "QATAR",
        "ROMANIA",
        "RUSSIA",
        "RWANDA",
        "SAINT KITTS AND NEVIS",
        "SAINT LUCIA",
        "SAINT VINCENT AND THE GRENADINES",
        "SAMOA",
        "SAN MARINO",
        "SAO TOME AND PRINCIPE",
        "SAUDI ARABIA",
        "SENEGAL",
        "SERBIA",
        "SEYCHELLES",
        "SIERRA LEONE",
        "SINGAPORE",
        "SLOVAKIA",
        "SLOVENIA",
        "SOLOMON ISLANDS",
        "SOMALIA",
        "SOUTH AFRICA",
        "SOUTH SUDAN",
        "SPAIN",
        "SRI LANKA",
        "SUDAN",
        "SURINAME",
        "SWEDEN",
        "SWITZERLAND",
        "SYRIA",
        "TAIWAN",
        "TAJIKISTAN",
        "TANZANIA",
        "THAILAND",
        "TOGO",
        "TONGA",
        "TRINIDAD AND TOBAGO",
        "TUNISIA",
        "TURKEY",
        "TURKMENISTAN",
        "TUVALU",
        "UGANDA",
        "UKRAINE",
        "UNITED ARAB EMIRATES",
        "UNITED KINGDOM",
        "UNITED STATES",
        "URUGUAY",
        "UZBEKISTAN",
        "VANUATU",
        "VATICAN CITY",
        "VENEZUELA",
        "VIETNAM",
        "YEMEN",
        "ZAMBIA",
        "ZIMBABWE",
      ],
    },
    stateOrProvince: {
      type: String,
      // required: true,
      default: "",
    },
    website: {
      type: String,
      // required: true,
      default: "",
    },
    schoolUrl: {
      type: String,
      // required: true
    },
    schoolLogo: {
      type: String,
      // required: true,
      default: ""
    },
    schoolContactPhone: {
      type: String,
      // required: true,
      default: "",
    },
    schoolContactEmail: {
      type: String,
      // required: true,
      default: "",
    },
    technicalContactPhone: {
      type: String,
      default: "",
    },
    technicalContactEmail: {
      type: String,
      default: "",
    },
    proprietorSignature: {
      type: String,
      // required: true,
      default: ""
    },
    // institutionRegistrationToken: {
    //   type: String,
    //   required: true,
    // },
    adminFirstName: {
      type: String,
      required: true
  },
  adminLastName: {
      type: String,
      required: true
  },
  adminProfilePhoto: {
      type: String,
      default: "https://w7.pngwing.com/pngs/205/731/png-transparent-default-avatar-thumbnail.png"
  },
  adminEmail: {
      type: String,
      required: true,
      unique: true
  },
  adminPhone: {
      type: String,
      required: true,
      unique: true
  },
  adminPassword: {
      type: String,
      required: true
  },
  adminGender: {
      type: String,
      required: true,
      enum: ["MALE", "FEMALE"]
  },
  adminDateOfBirth: {
    type: String,
    default: ""
  },
  role: {
      type: String,
      enum: ["admin", "user"],
      default: "admin"
  }
  },
  {
    timestamps: true,
  }
);

export default model("Institution", institutionSchema);
